package spamdetector

// Define spam phrases that indicate potential spam content
var spamPhrases = []string{
    "cialis", "buy now", "cheap pills", "discount meds", 
    "bitcoin investment", "get rich quick", "earn money fast", 
    "work from home", "make money online", "guaranteed income",
    "no prescription", "weight loss", "lose weight fast", "miracle cure",
    "enlargement", "replica watches", "free trial", "limited time offer",
    "casino", "gambling", "lottery winner", "nigerian prince", "wire transfer",
    "congratulations you won", "unclaimed inheritance",
    "no credit check", "payday loan", "adult content",
    "discount prices", "act now", "satisfaction guaranteed", "free access",
    "meet singles", "dating site", "hot girls", "loan approval", "debt consolidation",
    "credit repair", "eliminate debt", "best rates", "lowest price",
    "free installation", "free hosting", "free domain", "free website",
    "investment opportunity", "business opportunity", "passive income", 
	"100% more", "100% free", "100% satisfied", "additional income", 
	"be your own boss", "best price", "big bucks", "cash bonus", 
	"cents on the dollar", "consolidate debt", "double your cash", 
	"double your income", "earn extra cash", "earn money", "eliminate bad credit", 
	"extra cash", "extra income", "expect to earn", "fast cash", "financial freedom", 
	"free access", "free consultation", "free gift", "free info", 
	"free investment", "free membership", "free money", "free preview", "free quote", 
	"free movies", "free videos", "free crypto", "free bitcoin", 
	"free robux", "free cheats", "free hacks", "full refund", "get out of debt", 
	"get paid", "giveaway", "increase sales", "increase traffic", 
	"incredible deal", "lower rates", "make money",
	"miracle", "money back", "once in a lifetime", "one time", "pennies a day", 
	"potential earnings", "prize", "promise", "pure profit", "risk-free", 
	"save big money", "save up to", "special promotion", 
	"act now", "become a member", "call now", "click below", "click here", 
	"get it now", "do it today", "don't delete", "exclusive deal", "get started now", 
	"important information regarding", "information you requested", "instant", 
	"new customers only", "order now", "please read", "see for yourself", "sign up free", 
	"take action", "this won't last", "urgent", "what are you waiting for?", "while supplies last", 
	"will not believe your eyes", "winner", "winning", "you are a winner", "you have been selected", 
	"buy direct", "check or money order", "congratulations", "cures", 
	"dear friend", "direct email", "direct marketing", "hidden charges", "human growth hormone", 
	"internet marketing", "mass email", "meet singles", "multi-level marketing", 
	"no catch", "no cost", "no fees", "no gimmick", "no hidden costs", 
	"no hidden fees", "no interest", "no investment", "no obligation", "no purchase necessary", 
	"no questions asked", "no strings attached", "not junk", "notspam", "requires initial investment", 
	"this isn't a scam", "this isn't junk", "this isn't spam", 
	"undisclosed", "unsecured credit", "unsecured debt", "unsolicited", "valium", "viagra", 
	"vicodin", "weight loss", "xanax", "ad", "all new", "as seen on", "bargain", "beneficiary", 
	"billing", "bonus", "cards accepted", "cash", "cheap", "claims", "compare rates", 
	"credit card offers", "income", "loans", "marketing solution", 
	"mortgage rates", "name brand", "offer", "online marketing", "opt in", "pre-approved", 
	"quote", "rates", "refinance", "score", "warranty", "work from home", "% off", "buy now", 
	"call free", "clearance", "guaranteed", "limited time", "apply now", "bad credit", 
	"loan", "mortgage", "lose weight", "miracle cure", "natural healing", "pain relief", 
	"instant results", "cash bonus", "discount", "money back", "order now", 
	"click here", "free trial", "no catch", "opt-in", "free vacation", "cruise", 
	"discount travel", "book now", "jackpot", "win big", "bonus", "free chips", 
	"no risk", "free spins", "no deposit bonus", "guaranteed win", "instant payout", "xxx", "porn", 
	"in your area", "sex", "naked girls", "milf", "hentai", "gangbang", "pussy", "cock", "tits", 
	"orgy", "bukkake", "bondage", "cum", "masturbate", "masturbation", "striptease", "download cheats", 
	"download hacks", "malware detected", "virus detected", "hacker detected", "100% legit", "you have won",
	"you win", "survey", "excellent value", "cams", "horny", "jerk off", "ozempic", "chemtrails", "onlyfans",
}

var weights = map[string]int{
	"malware detected": 3, 
	"virus detected": 3, 
	"hacker detected": 2,
	"earn money fast": 2,
	"congratulations you won": 3, 
	"free gift": 3,
	"free money": 2,
	"free movies": 3, 
	"free crypto": 3, 
	"free bitcoin": 3, 
	"free robux": 3, 
	"free cheats": 3, 
	"free hacks": 3,
	"free spins": 3,
	"instant payout": 2,
	"xxx": 2,
	"porn": 3, 
	"in your area": 2, 
	"cams": 2,
	"horny": 3,
	"milf": 2,
	"hentai": 2,
	"gangbang": 4,
	"pussy": 2,
	"cock": 2,
	"tits": 2,
	"orgy": 2,
	"bukkake": 4,
	"bondage": 3,
	"jerk off": 3,
	"cum": 3,
	"credit repair": 2,
	"cialis": 2,
	"viagra": 2,
	"cash bonus": 3,
	"jackpot": 2,
	"human growth hormone": 3,
	"pure profit": 2, 
	"risk-free": 2,
	"make money online": 4,
	"lottery winner": 2,
	"no strings attached": 3,
	"you have been selected": 2,
	"lose weight": 2, 
	"miracle cure": 2,
	"this isn't a scam": 2, 
	"this isn't junk": 2, 
	"this isn't spam": 2,
	"enlargement": 2,
	"free vacation": 2,
	"you have won": 3,
	"you win": 3,
	"ozempic": 2,
}